#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: springdb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: userpassword
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  springapp:
#    build: .
#    container_name: springapp-container
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: userpassword
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#
#volumes:
#  mysql-data:

services:
  springapp:
    build: .
    container_name: springapp-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql.railway.internal:3306/railway  # Railway에서 제공하는 DATABASE_URL 환경 변수를 사용
      SPRING_DATASOURCE_USERNAME: root  # Railway에서 제공하는 DATABASE_USERNAME 환경 변수
      SPRING_DATASOURCE_PASSWORD: VhKFTnxsqhSqPdmQMDSpNiDDnVHecBwh  # Railway에서 제공하는 DATABASE_PASSWORD 환경 변수
    ports:
      - "8080:8080"
    depends_on:
      - mysql  # MySQL 서비스는 필요 없으므로, 제거