package com.example.demo

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional

@Service
class TransferService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private val userRepository: UserRepository? = null

    @Transactional
    fun transfer(fromId: String, toId: String, amount: Long): Boolean {
        val fromUser = userRepository!!.findUserwithlock(fromId)
        val toUser = userRepository.findUserwithlock(toId)

        if (fromUser == null || toUser == null) return false

        val fs: Int = userRepository.changeBalance(fromId, -amount)
        val ts: Int = userRepository.changeBalance(toId, amount)

        return fs==1&&ts==1
    }
}