package com.example.demo

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.transaction.annotation.Transactional

class TransferService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private val userRepository: UserRepository? = null

    @Transactional
    fun transfer(fromId: String, toId: String, amount: Long): Boolean {
        val fromUser = userRepository!!.findUserwithlock(fromId)
        val toUser = userRepository.findUserwithlock(toId)

        if (fromUser == null || toUser == null) return false

        return userRepository.transfer(fromId, toId, amount)==2
    }
}